import React from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const PrivacyPolicy = () => {
  return (
    <div className="relative min-h-screen bg-cloud-dark text-gray-200">
      <Navbar />
      
      {/* Simple header */}
      <div className="bg-gray-900 border-b border-gray-800 py-16 mt-16">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl md:text-4xl font-bold text-white">Privacy Policy</h1>
              <p className="text-gray-400 mt-2">Last updated: May 11, 2025</p>
            </div>
            <div className="hidden md:block">
              <img 
                src="/logo.png" 
                alt="SCTA Technologies Logo" 
                className="h-10 w-auto opacity-70"
              />
            </div>
          </div>
        </div>
      </div>
      
      {/* Content with card design */}
      <div className="container mx-auto px-4 py-12">
        <div className="bg-gray-900 rounded-lg shadow-xl border border-gray-800 p-6 md:p-10">
          <div className="prose prose-lg prose-invert max-w-none prose-headings:text-cloud-purple prose-a:text-cloud-blue">
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
            
            <div className="my-8 p-6 bg-gray-800/70 border-l-4 border-cloud-blue rounded-r-lg">
              <h2 className="text-2xl font-bold text-cloud-blue mt-0">Interpretation and Definitions</h2>
              <h3 className="text-xl font-semibold text-cloud-blue">Interpretation</h3>
              <p className="mb-0 text-gray-300">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            </div>
            
            <h3 className="text-xl font-semibold text-cloud-purple">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul className="space-y-3 list-none">
              {[
                { term: "Account", def: "means a unique account created for You to access our Service or parts of our Service." },
                { term: "Affiliate", def: "means an entity that controls, is controlled by or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority." },
                { term: "Company", def: "(referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to Sctatech technologies, #172, Kamaraj Nagar, OMR Chennai, India – 600119." },
                { term: "Cookies", def: "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses." },
                { term: "Country", def: "refers to: Tamil Nadu, India" },
                { term: "Device", def: "means any device that can access the Service such as a computer, a cellphone or a digital tablet." },
                { term: "Personal Data", def: "is any information that relates to an identified or identifiable individual." },
                { term: "Service", def: "refers to the Website." },
                { term: "Service Provider", def: "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used." },
                { term: "Usage Data", def: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." },
                { term: "Website", def: "refers to Sctatech, accessible from http://sctatech.com/" },
                { term: "You", def: "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." }
              ].map((item, i) => (
                <li key={i} className="p-4 bg-gray-800 rounded-lg border border-gray-700">
                  <p className="mb-1"><strong className="text-cloud-purple">{item.term}</strong> {item.def}</p>
                </li>
              ))}
            </ul>

            <div className="my-8 p-6 bg-gray-800/70 border-l-4 border-cloud-purple rounded-r-lg">
              <h2 className="text-2xl font-bold text-cloud-purple mt-0">Collecting and Using Your Personal Data</h2>
            </div>
            
            <h3 className="text-xl font-semibold text-cloud-purple">Types of Data Collected</h3>
            
            <h4 className="text-lg font-semibold text-cloud-blue mt-6">Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul className="space-y-2 list-disc pl-6 text-gray-300">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-lg font-semibold text-cloud-blue mt-6">Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

            <h4 className="text-lg font-semibold text-cloud-blue mt-6">Tracking Technologies and Cookies</h4>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-6">
              <div className="bg-gray-800 p-5 rounded-lg border border-gray-700">
                <h5 className="font-semibold text-cloud-purple">Cookies or Browser Cookies</h5>
                <p className="mb-0 text-gray-300">A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>
              </div>
              <div className="bg-gray-800 p-5 rounded-lg border border-gray-700">
                <h5 className="font-semibold text-cloud-purple">Web Beacons</h5>
                <p className="mb-0 text-gray-300">Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages or opened an email and for other related website statistics.</p>
              </div>
            </div>

            <div className="my-6 p-5 bg-gray-800/70 border-l-4 border-cloud-blue rounded-r-lg">
              <p className="mb-0 text-gray-300">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on <a href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies" target="_blank" className="font-medium text-cloud-blue hover:text-blue-400">TermsFeed website</a>.</p>
            </div>

            <h3 className="text-xl font-semibold text-cloud-purple mt-10">Cookie Types We Use</h3>
            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
            
            <div className="space-y-6 my-6">
              <div className="bg-gray-800 p-5 rounded-lg shadow-lg border border-gray-700 border-l-4 border-l-cloud-purple">
                <h4 className="font-semibold text-cloud-purple mb-2">Necessary / Essential Cookies</h4>
                <div className="text-sm text-gray-400 mb-2">
                  <span className="mr-4">Type: Session Cookies</span>
                  <span>Administered by: Us</span>
                </div>
                <p className="mb-0 text-gray-300">These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided.</p>
              </div>
              
              <div className="bg-gray-800 p-5 rounded-lg shadow-lg border border-gray-700 border-l-4 border-l-cloud-blue">
                <h4 className="font-semibold text-cloud-blue mb-2">Cookies Policy / Notice Acceptance Cookies</h4>
                <div className="text-sm text-gray-400 mb-2">
                  <span className="mr-4">Type: Persistent Cookies</span>
                  <span>Administered by: Us</span>
                </div>
                <p className="mb-0 text-gray-300">These Cookies identify if users have accepted the use of cookies on the Website.</p>
              </div>
              
              <div className="bg-gray-800 p-5 rounded-lg shadow-lg border border-gray-700 border-l-4 border-l-cloud-purple">
                <h4 className="font-semibold text-cloud-purple mb-2">Functionality Cookies</h4>
                <div className="text-sm text-gray-400 mb-2">
                  <span className="mr-4">Type: Persistent Cookies</span>
                  <span>Administered by: Us</span>
                </div>
                <p className="mb-0 text-gray-300">These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience.</p>
              </div>
            </div>

            <div className="my-8 p-6 bg-gradient-to-r from-cloud-purple/20 to-cloud-blue/20 rounded-lg border border-gray-700">
              <h2 className="text-2xl font-bold text-white mt-0">Contact Us</h2>
              <p className="mb-0 text-gray-300">If you have any questions about this Privacy Policy, You can contact us:</p>
              <ul className="space-y-3 mt-4 mb-0">
                <li className="flex items-center">
                  <span className="inline-block mr-3 text-cloud-purple text-xl">✉️</span> 
                  <span className="text-gray-300">By email: <a href="mailto:connect@sctatech.com" className="font-medium text-cloud-blue hover:text-blue-400">connect@sctatech.com</a></span>
                </li>
                <li className="flex items-center">
                  <span className="inline-block mr-3 text-cloud-purple text-xl">🌐</span> 
                  <span className="text-gray-300">By visiting: <a href="https://www.sctatech.com/contact" rel="external nofollow noopener" target="_blank" className="font-medium text-cloud-blue hover:text-blue-400">https://www.sctatech.com/contact</a></span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      
      <Footer />
    </div>
  );
};

export default PrivacyPolicy; 