"""v2

Revision ID: 0a82f4793b6f
Revises: 35271ca36a09
Create Date: 2025-06-14 11:06:33.810542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a82f4793b6f'
down_revision = '35271ca36a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('interested', sa.String(length=120), nullable=True),
    sa.Column('applying_position', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('experience', sa.String(length=120), nullable=True),
    sa.Column('ctc', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('qualification', sa.String(length=120), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('relevant_experience', sa.String(length=120), nullable=True),
    sa.Column('notice_period', sa.String(length=120), nullable=True),
    sa.Column('preferred_time', sa.String(length=120), nullable=True),
    sa.Column('security_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_applications')
    # ### end Alembic commands ###
