"""v2

Revision ID: 9f222d72d5bb
Revises: fa92bb25a1dc
Create Date: 2025-06-14 13:42:35.486801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f222d72d5bb'
down_revision = 'fa92bb25a1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_experience', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('current_ctc', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('expected_ctc', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_negotiable', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('reason_for_change', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('current_location', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('willing_to_relocate', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('preferred_contact_time', sa.String(length=120), nullable=False))
        batch_op.alter_column('applying_position',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('qualification',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('skills',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('relevant_experience',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('notice_period',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('security_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('experience')
        batch_op.drop_column('preferred_time')
        batch_op.drop_column('reason')
        batch_op.drop_column('interested')
        batch_op.drop_column('ctc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ctc', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('interested', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('preferred_time', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.VARCHAR(length=120), nullable=True))
        batch_op.alter_column('security_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('notice_period',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('relevant_experience',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('skills',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('qualification',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('applying_position',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('preferred_contact_time')
        batch_op.drop_column('willing_to_relocate')
        batch_op.drop_column('current_location')
        batch_op.drop_column('reason_for_change')
        batch_op.drop_column('is_negotiable')
        batch_op.drop_column('expected_ctc')
        batch_op.drop_column('current_ctc')
        batch_op.drop_column('total_experience')

    # ### end Alembic commands ###
