"""v2

Revision ID: fa92bb25a1dc
Revises: 0a82f4793b6f
Create Date: 2025-06-14 12:49:07.275189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa92bb25a1dc'
down_revision = '0a82f4793b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_applications', schema=None) as batch_op:
        batch_op.alter_column('applying_position',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_applications', schema=None) as batch_op:
        batch_op.alter_column('applying_position',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
